//! End-to-end core pipeline: enumerate → annotate → classify → verify → emit.

use std::collections::HashSet;

use differential_schema as schema;

use crate::EngineError;
use crate::config::Config;
use crate::document::{SourceInfo, assemble, mark_generated};
use crate::gitio::Repo;
use crate::invariants::{InvariantReport, check_all};
use crate::parse::parse_canonical;
use crate::rename_view::{merge_raw, merge_renames, parse_raw_z, parse_renames_z};
use crate::shape::partition;

pub struct PipelineOutput {
    pub base: String,
    pub head: String,
    pub report: InvariantReport,
    /// `None` iff an invariant failed — no document is emitted on a violation.
    pub document: Option<schema::PlanDocument>,
}

/// Run the milestone-1 pipeline (stages: enumerate, classify) over `base..head`.
///
/// Config is consulted ONLY for classification hints; enumeration is total and
/// runs before config is even looked at (ADR 0012).
pub fn run_pipeline(
    repo: &Repo,
    base_rev: &str,
    head_rev: &str,
    kind: schema::SourceKind,
    config: &Config,
) -> Result<PipelineOutput, EngineError> {
    let base = repo.rev_parse(base_rev)?;
    let head = repo.rev_parse(head_rev)?;

    // Canonical metadata: authoritative modes, full oids, dispositions.
    let raw = repo.run(
        [
            "diff-tree",
            "-r",
            "-z",
            "--raw",
            "--full-index",
            "--no-renames",
            &base,
            &head,
        ],
        None,
    )?;
    let records = parse_raw_z(&raw)?;
    let dispositions = records
        .iter()
        .map(|r| {
            let d = match r.status {
                b'A' => crate::model::Disposition::Added,
                b'D' => crate::model::Disposition::Deleted,
                _ => crate::model::Disposition::Modified,
            };
            (r.path.clone(), d)
        })
        .collect();

    // Canonical enumeration: every file, no exclusions (ADR 0005).
    let patch = repo.run(
        [
            "diff-tree",
            "-r",
            "-U0",
            "--no-renames",
            "--no-color",
            "--no-ext-diff",
            &base,
            &head,
        ],
        None,
    )?;
    let mut view = parse_canonical(&patch, &dispositions)?;
    merge_raw(&mut view, &records)?;

    // Rename-detected annotations (ADR 0003).
    let renames_raw = repo.run(
        ["diff-tree", "-r", "-M", "-z", "--name-status", &base, &head],
        None,
    )?;
    merge_renames(&mut view, &parse_renames_z(&renames_raw)?);

    // Generated hints: gitattributes + config + builtins.
    let attr_marked = attr_marked_paths(repo, config, &view)?;
    mark_generated(&mut view, config, &attr_marked);

    // Mechanical partition: 100% coverage by construction.
    let part = partition(&view);

    // Invariants 1–4; no document on violation.
    let report = check_all(repo, &base, &head, &view)?;
    let document = if report.all_ok() {
        Some(assemble(
            &view,
            &part,
            &SourceInfo {
                kind,
                base: base.clone(),
                head: head.clone(),
            },
            &report,
        )?)
    } else {
        None
    };

    Ok(PipelineOutput {
        base,
        head,
        report,
        document,
    })
}

/// Paths marked generated by any of the configured gitattributes names.
/// Note: `check-attr` consults the worktree/index `.gitattributes`, not the
/// reviewed revisions — acceptable for a hint that never affects enumeration.
fn attr_marked_paths(
    repo: &Repo,
    config: &Config,
    view: &crate::model::DiffView,
) -> Result<HashSet<Vec<u8>>, EngineError> {
    let mut marked = HashSet::new();
    if view.files.is_empty() {
        return Ok(marked);
    }
    let mut stdin: Vec<u8> = Vec::new();
    for f in &view.files {
        stdin.extend_from_slice(&f.path);
        stdin.push(0);
    }
    for attr in &config.attributes {
        let out = repo.run(["check-attr", "-z", "--stdin", attr.as_str()], Some(&stdin))?;
        // -z output: path NUL attr NUL value NUL ...
        let fields: Vec<&[u8]> = out.split(|&b| b == 0).collect();
        for triple in fields.chunks_exact(3) {
            let (path, value) = (triple[0], triple[2]);
            if value != b"unspecified" && value != b"unset" && value != b"false" {
                marked.insert(path.to_vec());
            }
        }
    }
    Ok(marked)
}
